export enum AuthTrackingStages {
  STARTED = "Started",
  SUBMITTED = "Submitted",
  IN_PROGRESS = "In Progress",
  PENDING = "Pending",
  APPROVED = "Approved",
  DENIED = "Denied",
  CLOSED = "Closed",
  PARTIALLY_APPROVED = "Partially Approved",
  NEW = "New",
  ASSIGNED = "Assigned",
  ASSIGNING = "Assigning",
  AUTHORIZED = "Authorized",
  FINANCIAL = "Financial",
  HOLD = "On hold",
  QUERY = "Queried",
  PHARM_FILL = "Pharmacy Filled",
  FINANCIAL_REVIEW = "Financial Review",
}
