export enum ExternalAuthStatus {
  AUTH_STATUS = "Auth Status",
  REQUIRED = "Required",
  PENDING = "Pending",
  AUTH_BY_RISA = "Auth by RISA",
  AUTH_ON_FILE = "Auth on file",
  NAR = "NAR",
  AUTHORIZED_BY_ONSHORE_TEAM = "Authorized by onshore team",
  EXISTING_DENIAL = "Existing denial",
  DENIAL_AFTER_QUERY = "Denial after query",
  DENIAL_BY_RISA = "Denial by RISA",
  QUERY = "Query",
  WORKED_BY_ONSHORE_TEAM = "Worked by onshore team",
  DRUG_REMOVED = "Drug removed",
  DRUG_CHANGED = "Drug changed",
  INSURANCE_CHANGED = "Insurance changed",
  TREATMENT_PLAN_CHANGED = "Treatment plan changed",
  DOS_CHANGED = "DOS changed",
  AUTH_REQUIRED = "Auth required",
  HOLD = "Hold",
}
