export interface SchemaField {
  id: number;
  fieldPath: string;
  type: string;
  description: string;
  example: string;
}

export interface SchemaSection {
  title: string;
  key: string;
  description: string;
  fields: SchemaField[];
}

export const defaultSchema: SchemaSection[] = [
  {
    title: "Top-Level Fields",
    key: "top_level",
    description: "Core identifiers",
    fields: [
      {
        id: 1,
        fieldPath: "identifier",
        type: "STRING",
        description: "Unique case identifier",
        example: "uuid-string",
      },
      {
        id: 2,
        fieldPath: "org_id",
        type: "STRING",
        description: "Organization identifier",
        example: "L0ju12UjNQ7e2y7zYZm1",
      },
      {
        id: 3,
        fieldPath: "portal_id",
        type: "STRING",
        description: "Portal identifier",
        example: "portal-123",
      },
    ],
  },
  {
    title: "Workflow",
    key: "workflow",
    description: "Case workflow status, assignments, and actions",
    fields: [
      {
        id: 10,
        fieldPath: "workflow.status",
        type: "STRING",
        description: "Current workflow status",
        example: "Pending",
      },
      {
        id: 11,
        fieldPath: "workflow.final_outcome",
        type: "STRING",
        description: "Final outcome of the case",
        example: "Approved",
      },
      {
        id: 12,
        fieldPath: "workflow.comment",
        type: "STRING",
        description: "Workflow comment",
        example: "Reviewed by agent",
      },
      {
        id: 13,
        fieldPath: "workflow.error_text",
        type: "STRING",
        description: "Error text if any",
        example: "",
      },
      {
        id: 14,
        fieldPath: "workflow.type",
        type: "STRING",
        description: "Workflow type (Internal/External)",
        example: "Internal",
      },
      {
        id: 15,
        fieldPath: "workflow.review_type",
        type: "STRING",
        description: "Review type",
        example: "Standard",
      },
      {
        id: 16,
        fieldPath: "workflow.assignee_id",
        type: "STRING",
        description: "Assigned user ID",
        example: "user-456",
      },
      {
        id: 17,
        fieldPath: "workflow.cmm_result_key",
        type: "STRING",
        description: "CoverMyMeds result key",
        example: "BFAB982C",
      },
      {
        id: 18,
        fieldPath: "workflow.patient_eligibility_check_status",
        type: "STRING",
        description: "Eligibility check status",
        example: "Verified",
      },
      {
        id: 19,
        fieldPath: "workflow.is_substitution_allowed",
        type: "BOOL",
        description: "Whether substitution is allowed",
        example: "true",
      },
      {
        id: 20,
        fieldPath: "workflow.date_of_service",
        type: "STRING",
        description: "Date of service",
        example: "2026-01-15",
      },
    ],
  },
  {
    title: "Workflow — Suggested Actions",
    key: "workflow_suggested_actions",
    description: "Suggested next steps from workflow (REPEATED)",
    fields: [
      {
        id: 25,
        fieldPath: "workflow.suggested_actions.next_steps",
        type: "STRING",
        description: "Suggested next steps text",
        example: "Submit appeal",
      },
      {
        id: 26,
        fieldPath: "workflow.suggested_actions.next_steps_summary",
        type: "STRING",
        description: "Next steps summary",
        example: "Appeal recommended",
      },
      {
        id: 27,
        fieldPath: "workflow.suggested_actions.alternate_insurance",
        type: "STRING",
        description: "Alternate insurance option",
        example: "Express Scripts",
      },
      {
        id: 28,
        fieldPath: "workflow.suggested_actions.alternate_insurance_form_name",
        type: "STRING",
        description: "Alternate insurance form name",
        example: "PA Form v2",
      },
      {
        id: 29,
        fieldPath: "workflow.suggested_actions.key_from_outcome",
        type: "STRING",
        description: "Key extracted from outcome",
        example: "KEY123",
      },
      {
        id: 30,
        fieldPath: "workflow.suggested_actions.phone_from_outcome",
        type: "STRING",
        description: "Phone from outcome",
        example: "800-555-0100",
      },
      {
        id: 31,
        fieldPath: "workflow.suggested_actions.fax_from_outcome",
        type: "STRING",
        description: "Fax from outcome",
        example: "800-555-0101",
      },
    ],
  },
  {
    title: "Drug",
    key: "drug",
    description: "Drug/medication details",
    fields: [
      {
        id: 40,
        fieldPath: "drug.drug_name",
        type: "STRING",
        description: "Drug name (matched)",
        example: "Injectafer",
      },
      {
        id: 41,
        fieldPath: "drug.drug_name_onco_emr",
        type: "STRING",
        description: "Drug name from OncoEMR",
        example: "Injectafer 750mg",
      },
      {
        id: 42,
        fieldPath: "drug.drug_fetched_from",
        type: "STRING",
        description: "Source of drug data",
        example: "OncoEMR",
      },
      {
        id: 43,
        fieldPath: "drug.drug_confidence_score",
        type: "FLOAT",
        description: "Drug match confidence (0-1)",
        example: "0.95",
      },
      {
        id: 44,
        fieldPath: "drug.drug_picked_thinking",
        type: "STRING",
        description: "LLM reasoning for drug pick",
        example: "Matched by NDC",
      },
      {
        id: 45,
        fieldPath: "drug.ndc_number",
        type: "STRING",
        description: "National Drug Code",
        example: "00517-0540-01",
      },
      {
        id: 46,
        fieldPath: "drug.quantity",
        type: "FLOAT",
        description: "Drug quantity",
        example: "750",
      },
      {
        id: 47,
        fieldPath: "drug.quantity_qualifier",
        type: "STRING",
        description: "Quantity qualifier (mg, mL, etc.)",
        example: "mg",
      },
      {
        id: 48,
        fieldPath: "drug.days_supply",
        type: "INTEGER",
        description: "Days of supply",
        example: "30",
      },
    ],
  },
  {
    title: "Prescription",
    key: "prescription",
    description: "Prescription details",
    fields: [
      {
        id: 50,
        fieldPath: "prescription.description",
        type: "STRING",
        description: "Prescription description",
        example: "Iron deficiency anemia treatment",
      },
      {
        id: 51,
        fieldPath: "prescription.prescription_date",
        type: "STRING",
        description: "Prescription date",
        example: "2026-01-10",
      },
      {
        id: 52,
        fieldPath: "prescription.instructions",
        type: "STRING",
        description: "Dosing instructions",
        example: "Infuse over 15 min",
      },
      {
        id: 53,
        fieldPath: "prescription.dispense_qty",
        type: "STRING",
        description: "Dispense quantity",
        example: "750",
      },
      {
        id: 54,
        fieldPath: "prescription.dispense_qty_string",
        type: "STRING",
        description: "Dispense quantity (display)",
        example: "750 mg",
      },
      {
        id: 55,
        fieldPath: "prescription.refill_qty",
        type: "STRING",
        description: "Refill quantity",
        example: "2",
      },
      {
        id: 56,
        fieldPath: "prescription.refill_qty_string",
        type: "STRING",
        description: "Refill quantity (display)",
        example: "2 refills",
      },
      {
        id: 57,
        fieldPath: "prescription.is_related_drug_match",
        type: "BOOL",
        description: "Whether related drug was matched",
        example: "true",
      },
    ],
  },
  {
    title: "Patient",
    key: "patient",
    description: "Patient demographic information",
    fields: [
      {
        id: 60,
        fieldPath: "patient.patient_mrn",
        type: "STRING",
        description: "Medical Record Number",
        example: "MRN12345",
      },
      {
        id: 61,
        fieldPath: "patient.first_name",
        type: "STRING",
        description: "Patient first name",
        example: "John",
      },
      {
        id: 62,
        fieldPath: "patient.last_name",
        type: "STRING",
        description: "Patient last name",
        example: "Smith",
      },
      {
        id: 63,
        fieldPath: "patient.full_name",
        type: "STRING",
        description: "Patient full name",
        example: "John Smith",
      },
      {
        id: 64,
        fieldPath: "patient.dob",
        type: "STRING",
        description: "Date of birth",
        example: "01/01/1970",
      },
      {
        id: 65,
        fieldPath: "patient.gender",
        type: "STRING",
        description: "Gender",
        example: "Male",
      },
      {
        id: 66,
        fieldPath: "patient.phone_number",
        type: "STRING",
        description: "Phone number",
        example: "212-555-0100",
      },
    ],
  },
  {
    title: "Patient — Address",
    key: "patient_address",
    description: "Patient address details",
    fields: [
      {
        id: 70,
        fieldPath: "patient.address.street1",
        type: "STRING",
        description: "Street line 1",
        example: "123 Main St",
      },
      {
        id: 71,
        fieldPath: "patient.address.street2",
        type: "STRING",
        description: "Street line 2",
        example: "Apt 4B",
      },
      {
        id: 72,
        fieldPath: "patient.address.city",
        type: "STRING",
        description: "City",
        example: "New York",
      },
      {
        id: 73,
        fieldPath: "patient.address.state",
        type: "STRING",
        description: "State",
        example: "NY",
      },
      {
        id: 74,
        fieldPath: "patient.address.zip",
        type: "STRING",
        description: "ZIP code",
        example: "10001",
      },
      {
        id: 75,
        fieldPath: "patient.address.full_address",
        type: "STRING",
        description: "Full address string",
        example: "123 Main St, New York, NY 10001",
      },
      {
        id: 76,
        fieldPath: "patient.address.city_state_zip",
        type: "STRING",
        description: "City, State ZIP",
        example: "New York, NY 10001",
      },
    ],
  },
  {
    title: "Provider",
    key: "provider",
    description: "Provider / prescriber details",
    fields: [
      {
        id: 80,
        fieldPath: "provider.first_name",
        type: "STRING",
        description: "Provider first name",
        example: "Robert",
      },
      {
        id: 81,
        fieldPath: "provider.last_name",
        type: "STRING",
        description: "Provider last name",
        example: "Anderson",
      },
      {
        id: 82,
        fieldPath: "provider.full_name",
        type: "STRING",
        description: "Provider full name",
        example: "Dr. Robert Anderson",
      },
      {
        id: 83,
        fieldPath: "provider.npi",
        type: "STRING",
        description: "National Provider Identifier",
        example: "1234567890",
      },
      {
        id: 84,
        fieldPath: "provider.credentials",
        type: "STRING",
        description: "Provider credentials",
        example: "MD",
      },
      {
        id: 85,
        fieldPath: "provider.practice_name",
        type: "STRING",
        description: "Practice name",
        example: "NYC Cancer Center",
      },
      {
        id: 86,
        fieldPath: "provider.speciality",
        type: "STRING",
        description: "Specialty",
        example: "Oncology",
      },
      {
        id: 87,
        fieldPath: "provider.phone",
        type: "STRING",
        description: "Provider phone",
        example: "212-555-0200",
      },
      {
        id: 88,
        fieldPath: "provider.fax",
        type: "STRING",
        description: "Provider fax",
        example: "212-555-0201",
      },
    ],
  },
  {
    title: "Provider — Address",
    key: "provider_address",
    description: "Provider address details",
    fields: [
      {
        id: 90,
        fieldPath: "provider.address.street1",
        type: "STRING",
        description: "Street line 1",
        example: "456 Park Ave",
      },
      {
        id: 91,
        fieldPath: "provider.address.street2",
        type: "STRING",
        description: "Street line 2",
        example: "Suite 200",
      },
      {
        id: 92,
        fieldPath: "provider.address.city",
        type: "STRING",
        description: "City",
        example: "New York",
      },
      {
        id: 93,
        fieldPath: "provider.address.state",
        type: "STRING",
        description: "State",
        example: "NY",
      },
      {
        id: 94,
        fieldPath: "provider.address.zip",
        type: "STRING",
        description: "ZIP code",
        example: "10022",
      },
    ],
  },
  {
    title: "Diagnosis",
    key: "diagnosis",
    description: "Diagnosis codes (REPEATED)",
    fields: [
      {
        id: 100,
        fieldPath: "diagnosis.diagnosis_codes.icd10_code",
        type: "STRING",
        description: "ICD-10 code",
        example: "D50.9",
      },
      {
        id: 101,
        fieldPath: "diagnosis.diagnosis_codes.description",
        type: "STRING",
        description: "Diagnosis description",
        example: "Iron deficiency anemia",
      },
      {
        id: 102,
        fieldPath: "diagnosis.diagnosis_codes.drug_name",
        type: "STRING",
        description: "Associated drug name",
        example: "Injectafer",
      },
      {
        id: 103,
        fieldPath: "diagnosis.diagnosis_codes.diag_date",
        type: "STRING",
        description: "Diagnosis date",
        example: "2025-12-01",
      },
      {
        id: 104,
        fieldPath: "diagnosis.diagnosis_codes.last_verified_date",
        type: "STRING",
        description: "Last verified date",
        example: "2026-01-10",
      },
      {
        id: 105,
        fieldPath: "diagnosis.diagnosis_codes.is_primary",
        type: "BOOL",
        description: "Is primary diagnosis",
        example: "true",
      },
      {
        id: 106,
        fieldPath: "diagnosis.diagnosis_codes.is_secondary",
        type: "BOOL",
        description: "Is secondary diagnosis",
        example: "false",
      },
      {
        id: 107,
        fieldPath: "diagnosis.diagnosis_codes.is_selected_for_form",
        type: "BOOL",
        description: "Selected for form",
        example: "true",
      },
      {
        id: 108,
        fieldPath: "diagnosis.diagnosis_codes.is_found_by_priority_order",
        type: "BOOL",
        description: "Found by priority order",
        example: "true",
      },
      {
        id: 109,
        fieldPath: "diagnosis.diagnosis_codes.source",
        type: "STRING",
        description: "Source of diagnosis",
        example: "OncoEMR",
      },
      {
        id: 110,
        fieldPath: "diagnosis.diagnosis_codes.confidence_score",
        type: "FLOAT",
        description: "Confidence score (0-1)",
        example: "0.92",
      },
      {
        id: 111,
        fieldPath: "diagnosis.diagnosis_codes.llm_thinking",
        type: "STRING",
        description: "LLM reasoning",
        example: "Matched from chart notes",
      },
    ],
  },
  {
    title: "Insurance",
    key: "insurance",
    description: "Insurance details and form info",
    fields: [
      {
        id: 120,
        fieldPath: "insurance.form_picked_flag",
        type: "STRING",
        description: "Form picked flag",
        example: "auto",
      },
      {
        id: 121,
        fieldPath: "insurance.patient_member_id",
        type: "STRING",
        description: "Patient member ID",
        example: "MEM123456",
      },
      {
        id: 122,
        fieldPath: "insurance.patient_rx_bin",
        type: "STRING",
        description: "Rx BIN",
        example: "610455",
      },
      {
        id: 123,
        fieldPath: "insurance.patient_rx_group",
        type: "STRING",
        description: "Rx Group",
        example: "RX1234",
      },
      {
        id: 124,
        fieldPath: "insurance.patient_rx_pcn",
        type: "STRING",
        description: "Rx PCN",
        example: "PCN001",
      },
      {
        id: 125,
        fieldPath: "insurance.patient_insurance_state",
        type: "STRING",
        description: "Insurance state",
        example: "NY",
      },
      {
        id: 126,
        fieldPath: "insurance.sftp_rx_bin",
        type: "STRING",
        description: "SFTP Rx BIN",
        example: "610455",
      },
      {
        id: 127,
        fieldPath: "insurance.sftp_member_id",
        type: "STRING",
        description: "SFTP member ID",
        example: "MEM123456",
      },
    ],
  },
  {
    title: "Insurance — Active Insurance",
    key: "insurance_active",
    description: "Active insurance record details",
    fields: [
      {
        id: 130,
        fieldPath: "insurance.active_insurance.insurance.insurer",
        type: "STRING",
        description: "Insurer name",
        example: "Express Scripts",
      },
      {
        id: 131,
        fieldPath: "insurance.active_insurance.insurance.plan_name",
        type: "STRING",
        description: "Plan name",
        example: "Gold PPO",
      },
      {
        id: 132,
        fieldPath: "insurance.active_insurance.insurance.plan_number",
        type: "STRING",
        description: "Plan number",
        example: "PLN001",
      },
      {
        id: 133,
        fieldPath: "insurance.active_insurance.insurance.policy_number",
        type: "STRING",
        description: "Policy number",
        example: "POL001",
      },
      {
        id: 134,
        fieldPath: "insurance.active_insurance.insurance.group_number",
        type: "STRING",
        description: "Group number",
        example: "GRP001",
      },
      {
        id: 135,
        fieldPath: "insurance.active_insurance.insurance.effective",
        type: "STRING",
        description: "Effective date",
        example: "2025-01-01",
      },
      {
        id: 136,
        fieldPath: "insurance.active_insurance.insurance.term",
        type: "STRING",
        description: "Term date",
        example: "2026-12-31",
      },
      {
        id: 137,
        fieldPath: "insurance.active_insurance.insurance.phone",
        type: "STRING",
        description: "Insurance phone",
        example: "800-555-0300",
      },
      {
        id: 138,
        fieldPath: "insurance.active_insurance.insurance.type",
        type: "STRING",
        description: "Insurance type",
        example: "PBM",
      },
      {
        id: 139,
        fieldPath: "insurance.active_insurance.insurance.retail_benefit",
        type: "STRING",
        description: "Retail benefit",
        example: "Yes",
      },
      {
        id: 140,
        fieldPath: "insurance.active_insurance.insurance.mail_order_benefit",
        type: "STRING",
        description: "Mail order benefit",
        example: "Yes",
      },
      {
        id: 141,
        fieldPath: "insurance.active_insurance.insurance.ltc",
        type: "STRING",
        description: "Long-term care",
        example: "No",
      },
      {
        id: 142,
        fieldPath: "insurance.active_insurance.insurance.specialty",
        type: "STRING",
        description: "Specialty benefit",
        example: "Yes",
      },
    ],
  },
  {
    title: "Documents",
    key: "documents",
    description: "Attached documents (REPEATED)",
    fields: [
      {
        id: 150,
        fieldPath: "documents.identifier",
        type: "STRING",
        description: "Document identifier",
        example: "doc-uuid",
      },
      {
        id: 151,
        fieldPath: "documents.patient_mrn",
        type: "STRING",
        description: "Patient MRN",
        example: "MRN12345",
      },
      {
        id: 152,
        fieldPath: "documents.created_at",
        type: "TIMESTAMP",
        description: "Creation timestamp",
        example: "2026-01-11T08:29:21Z",
      },
      {
        id: 153,
        fieldPath: "documents.document_name",
        type: "STRING",
        description: "Document name",
        example: "Lab Results",
      },
      {
        id: 154,
        fieldPath: "documents.file_path",
        type: "STRING",
        description: "File path / URL",
        example: "gs://bucket/path",
      },
      {
        id: 155,
        fieldPath: "documents.visit_date",
        type: "STRING",
        description: "Visit date",
        example: "2026-01-10",
      },
      {
        id: 156,
        fieldPath: "documents.document_type",
        type: "STRING",
        description: "Document type",
        example: "clinical_attachment",
      },
      {
        id: 157,
        fieldPath: "documents.signed_status_text",
        type: "STRING",
        description: "Signed status",
        example: "Signed",
      },
    ],
  },
  {
    title: "Questionnaire",
    key: "questionnaire",
    description: "Clinical questionnaire and answers",
    fields: [
      {
        id: 160,
        fieldPath: "questionnaire.document_name",
        type: "STRING",
        description: "Questionnaire document name",
        example: "PA Form v3",
      },
      {
        id: 161,
        fieldPath: "questionnaire.qa_confidence",
        type: "FLOAT",
        description: "QA confidence score (0-1)",
        example: "0.88",
      },
      {
        id: 162,
        fieldPath: "questionnaire.file_path",
        type: "STRING",
        description: "File path / URL",
        example: "gs://bucket/qa",
      },
      {
        id: 163,
        fieldPath: "questionnaire.questions.question",
        type: "STRING",
        description: "Question text",
        example: "Has patient tried alternative therapy?",
      },
      {
        id: 164,
        fieldPath: "questionnaire.questions.answer",
        type: "STRING",
        description: "Answer text",
        example: "Yes",
      },
      {
        id: 165,
        fieldPath: "questionnaire.questions.type",
        type: "STRING",
        description: "Question type",
        example: "multiple_choice",
      },
    ],
  },
  {
    title: "Denial Prediction",
    key: "denial_prediction",
    description: "AI denial prediction",
    fields: [
      {
        id: 170,
        fieldPath: "denial_prediction.prediction_summary",
        type: "STRING",
        description: "Prediction summary text",
        example: "Low risk of denial",
      },
      {
        id: 171,
        fieldPath: "denial_prediction.prediction_confidence",
        type: "FLOAT",
        description: "Prediction confidence (0-1)",
        example: "0.85",
      },
    ],
  },
  {
    title: "Response Status Information",
    key: "response_status_info",
    description: "Outcome / determination details",
    fields: [
      {
        id: 180,
        fieldPath: "response_status_information.denial_reason",
        type: "STRING",
        description: "Denial reason",
        example: "Medical necessity not established",
      },
      {
        id: 181,
        fieldPath: "response_status_information.denial_summary",
        type: "STRING",
        description: "Denial summary",
        example: "Insufficient documentation",
      },
      {
        id: 182,
        fieldPath: "response_status_information.auth_date",
        type: "STRING",
        description: "Authorization date",
        example: "2026-02-01",
      },
    ],
  },
  {
    title: "Metadata",
    key: "metadata",
    description: "Additional metadata",
    fields: [
      {
        id: 190,
        fieldPath: "metadata.pay_method",
        type: "STRING",
        description: "Payment method",
        example: "Insurance",
      },
      {
        id: 191,
        fieldPath: "metadata.filename",
        type: "STRING",
        description: "Source filename",
        example: "NYCBS_RXSM_20260108.csv",
      },
      {
        id: 192,
        fieldPath: "metadata.metadata.portal_name",
        type: "STRING",
        description: "Portal name",
        example: "CoverMyMeds",
      },
    ],
  },
];
