import { SampleDataModel } from "../data-model/sampleData";

export const sampleDataForUI: SampleDataModel[] = [
  {
    mrn: "4206249",
    identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
    prescription: {
      drug_days_supply: 30,
      drug_name: "Lupron",
      drug_quantity: 1,
    },
    diagnosis: {
      code: "C61",
      description:
        "Prostate Cancer (Genitourinary) - Clinical Stage IVB (AJCC v8) TNM: cTX, cNX, cM1b; Gleason Score - Primary: Unknown HCC",
    },
    questions: [
      {
        question:
          "Is the requested medication being used for the treatment of advanced prostate cancer (e.g., metastatic or biochemical recurrence)?",
        question_type: "multi-choice",
        options: ["Yes", "No"],
      },
      {
        question:
          "Is this request for continuation of prior therapy within the past 120 days?",
        question_type: "multi-choice",
        options: ["Yes", "No"],
      },
      {
        question:
          "Is the requested medication being used as androgen deprivation therapy (ADT)?",
        question_type: "multi-choice",
        options: [
          "Yes — single agent",
          "Yes — in combination with an antiandrogen",
          "No",
        ],
      },
      {
        question:
          "Has the patient tried or had an inadequate response/intolerance to any of the following preferred formulary alternatives?",
        question_type: "multi-choice",
        options: [
          "Orgovyx (relugolix)",
          "Eligard (leuprolide acetate)",
          "Firmagon (degarelix)",
          "None tried",
        ],
      },
      {
        question: "What is the requested quantity?",
        question_type: "multi-choice",
        options: ["≤ 1 box per 28 days", "> 1 box per 28 days"],
      },
    ],
    questions_for_ui: [
      {
        question:
          "Is the requested medication being used for the treatment of advanced prostate cancer (e.g., metastatic or biochemical recurrence)?",
        type: "multi-choice",
        options: ["Yes", "No"],
      },
      {
        question:
          "Is this request for continuation of prior therapy within the past 120 days?",
        type: "multi-choice",
        options: ["Yes", "No"],
      },
      {
        question:
          "Is the requested medication being used as androgen deprivation therapy (ADT)?",
        type: "multi-choice",
        options: [
          "Yes — single agent",
          "Yes — in combination with an antiandrogen",
          "No",
        ],
      },
      {
        question:
          "Has the patient tried or had an inadequate response/intolerance to any of the following preferred formulary alternatives?",
        type: "multi-choice",
        options: [
          "Orgovyx (relugolix)",
          "Eligard (leuprolide acetate)",
          "Firmagon (degarelix)",
          "None tried",
        ],
      },
      {
        question: "What is the requested quantity?",
        type: "multi-choice",
        options: ["≤ 1 box per 28 days", "> 1 box per 28 days"],
      },
    ],
    pdf_path: "/clinical_pdf/lupron.pdf",
    oncoemr_medicine_summary: [
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "Lupron Depot 7.5 mg intramuscular syringe kit",
        created_at: "2025-09-05 04:12:51.873646 UTC",
        drug_quantity: "1 EA",
        drug_refill_quantity: "11",
        regimen_instruction: "INJECT 7.5MG INTRAMUSCULAR EVERY MONTH",
        is_best_match: "true",
        is_substitution_allowed: "true",
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "cefuroxime axetil 500 mg tablet",
        created_at: "2025-09-05 04:12:51.918146 UTC",
        drug_quantity: "6 tablets",
        drug_refill_quantity: null,
        regimen_instruction:
          "Take one pill twice daily starting the day before your prostate biopsy",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "Enema 19 gram-7 gram/118 mL",
        created_at: "2025-09-05 04:12:51.965751 UTC",
        drug_quantity: "1 milliliters",
        drug_refill_quantity: null,
        regimen_instruction: "Use enema the morning of your prostate biopsy",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "enoxaparin 120 mg/0.8 mL subcutaneous syringe",
        created_at: "2025-09-05 04:12:52.008282 UTC",
        drug_quantity: "10 milliliters",
        drug_refill_quantity: null,
        regimen_instruction: "Inject one daily suBQ",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "omeprazole 20 mg tablet,delayed release",
        created_at: "2025-09-05 04:12:52.051925 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: "1 by mouth daily before meals",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "Entresto 24 mg-26 mg tablet",
        created_at: "2025-09-05 04:12:52.096616 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: "1 1/5 every day.",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "Claritin 10 mg tablet",
        created_at: "2025-09-05 04:12:52.141983 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: "1 p.o. q. day",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "dofetilide 500 mcg capsule",
        created_at: "2025-09-05 04:12:52.186552 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: "1 p.o. twice a day (BID)",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "warfarin 5 mg tablet",
        created_at: "2025-09-05 04:12:52.230193 UTC",
        drug_quantity: "90 tablets",
        drug_refill_quantity: "1",
        regimen_instruction: "1 p.o. q. day",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "dofetilide 500 mcg capsule",
        created_at: "2025-09-05 04:12:52.281315 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: "1 p.o. twice a day (BID)",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "Lasix 20 mg tablet",
        created_at: "2025-09-05 04:12:52.324399 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: "prn",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "EPLERENONE 25MG TABLETS",
        created_at: "2025-09-05 04:12:52.369392 UTC",
        drug_quantity: "45",
        drug_refill_quantity: null,
        regimen_instruction: "TAKE 1 TABLET BY MOUTH EVERY OTHER DAY",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "furosemide 20 mg tablet",
        created_at: "2025-09-05 04:12:52.414236 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: "5 DAYS A WEEK.",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "WARFARIN SOD 5MG TABLETS (PEACH)",
        created_at: "2025-09-05 04:12:52.457874 UTC",
        drug_quantity: "90 Tablet",
        drug_refill_quantity: "1",
        regimen_instruction: "TAKE 1 TABLET BY MOUTH EVERY DAY AS DIRECTED",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "furosemide 40 mg tablet",
        created_at: "2025-09-05 04:12:52.505806 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: "4 DAYS A WEEK",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "Lasix 40 mg tablet",
        created_at: "2025-09-05 04:12:52.551302 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: "ONLY TWO DAYS.",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "LISINOPRIL 2.5 MG TABS",
        created_at: "2025-09-05 04:12:52.603563 UTC",
        drug_quantity: "90",
        drug_refill_quantity: null,
        regimen_instruction: null,
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "WARFARIN SOD 5MG TABLETS (PEACH)",
        created_at: "2025-09-05 04:12:52.653176 UTC",
        drug_quantity: "90 Tablet",
        drug_refill_quantity: null,
        regimen_instruction: "TAKE 1 TABLET BY MOUTH EVERY DAY AS DIRECTED",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "furosemide 40 mg tablet",
        created_at: "2025-09-05 04:12:52.705738 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: null,
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "warfarin 2.5 mg tablet",
        created_at: "2025-09-05 04:12:52.754500 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: "6 DAYS.",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "WARFARIN SOD 5MG TABLETS (PEACH)",
        created_at: "2025-09-05 04:12:52.801768 UTC",
        drug_quantity: "90 Tablet",
        drug_refill_quantity: null,
        regimen_instruction: "TAKE 1 TABLET BY MOUTH EVERY DAY AS DIRECTED",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "WARFARIN SOD 5MG TABLETS (PEACH)",
        created_at: "2025-09-05 04:12:52.847228 UTC",
        drug_quantity: "30 Tablet",
        drug_refill_quantity: "5",
        regimen_instruction: "TAKE 1 TABLET BY MOUTH EVERY DAY AS DIRECTED",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "enoxaparin 120 mg/0.8 mL subcutaneous syringe",
        created_at: "2025-09-05 04:12:52.891981 UTC",
        drug_quantity: "8 milliliters",
        drug_refill_quantity: null,
        regimen_instruction: "Inject 120mg subcutaneously daily.",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "WARFARIN SOD 5MG TABLETS (PEACH)",
        created_at: "2025-09-05 04:12:52.937043 UTC",
        drug_quantity: "30 Tablet",
        drug_refill_quantity: "4",
        regimen_instruction: "TAKE 1 TABLET BY MOUTH EVERY DAY AS DIRECTED",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "WARFARIN SOD 5MG TABLETS (PEACH)",
        created_at: "2025-09-05 04:12:52.983215 UTC",
        drug_quantity: "30",
        drug_refill_quantity: "3",
        regimen_instruction: "TAKE 1 TABLET BY MOUTH EVERY DAY AS DIRECTED",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "WARFARIN SOD 5MG TABLETS (PEACH)",
        created_at: "2025-09-05 04:12:53.027287 UTC",
        drug_quantity: "30",
        drug_refill_quantity: null,
        regimen_instruction: "TAKE 1 TABLET BY MOUTH EVERY DAY AS DIRECTED",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "WARFARIN SOD 5MG TABLETS (PEACH)",
        created_at: "2025-09-05 04:12:53.072688 UTC",
        drug_quantity: "30",
        drug_refill_quantity: "4",
        regimen_instruction: "TAKE 1 TABLET BY MOUTH EVERY DAY AS DIRECTED",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "WARFARIN SOD 5MG TABLETS (PEACH)",
        created_at: "2025-09-05 04:12:53.118435 UTC",
        drug_quantity: "30",
        drug_refill_quantity: null,
        regimen_instruction: "TAKE 1 TABLET BY MOUTH EVERY DAY AS DIRECTED",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "METOPROLOL SUCCINATE ER 25 MG TB24",
        created_at: "2025-09-05 04:12:53.164867 UTC",
        drug_quantity: "90",
        drug_refill_quantity: null,
        regimen_instruction: null,
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "warfarin 5 mg tablet",
        created_at: "2025-09-05 04:12:53.207331 UTC",
        drug_quantity: "30 EA",
        drug_refill_quantity: "3",
        regimen_instruction: "TAKE 1 TABLET BY MOUTH ONCE A DAY AS DIRECTED",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "digoxin 62.5 mcg tablet",
        created_at: "2025-09-05 04:12:53.253728 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: "1 p.o. q. day",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "warfarin 5 mg tablet",
        created_at: "2025-09-05 04:12:53.300921 UTC",
        drug_quantity: "30 EA",
        drug_refill_quantity: "3",
        regimen_instruction: "TAKE 1 TABLET BY MOUTH ONCE A DAY AS DIRECTED",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "warfarin 5 mg tablet",
        created_at: "2025-09-05 04:12:53.345804 UTC",
        drug_quantity: "30",
        drug_refill_quantity: "3",
        regimen_instruction: "TAKE 1 TABLET BY MOUTH ONCE A DAY AS DIRECTED",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "warfarin 5 mg tablet",
        created_at: "2025-09-05 04:12:53.391008 UTC",
        drug_quantity: "30",
        drug_refill_quantity: "3",
        regimen_instruction: "TAKE 1 TABLET BY MOUTH ONCE A DAY AS DIRECTED",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "warfarin 5 mg tablet",
        created_at: "2025-09-05 04:12:53.437363 UTC",
        drug_quantity: "30 EA",
        drug_refill_quantity: "4",
        regimen_instruction: "TAKE 1 TABLET BY MOUTH ONCE A DAY AS DIRECTED",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "warfarin 5 mg tablet",
        created_at: "2025-09-05 04:12:53.481968 UTC",
        drug_quantity: "30",
        drug_refill_quantity: "4",
        regimen_instruction: "TAKE 1 TABLET BY MOUTH ONCE A DAY AS DIRECTED",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "warfarin 5 mg tablet",
        created_at: "2025-09-05 04:12:53.524916 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: "5mg 1x a week. 2.5mg 6 days a week",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "1daa1c4f-38f5-43ac-ac4c-0d213eba63c0",
        patient_mrn: "4206249",
        drug_name: "Lupron",
        regimen_description: "JARDIANCE 10MG TAB",
        created_at: "2025-09-05 04:12:53.567457 UTC",
        drug_quantity: "90",
        drug_refill_quantity: null,
        regimen_instruction: null,
        is_best_match: "false",
        is_substitution_allowed: null,
      },
    ],
    is_substitution_allowed: true,
  },
  {
    mrn: "8778374",
    identifier: "f5ca9b2e-728c-4b3e-a821-3576bfd01f80",
    prescription: {
      drug_days_supply: 28,
      drug_name: "Akynzeo",
      drug_quantity: 40,
    },
    diagnosis: {
      code: "R11.2",
      description: "Nausea with vomiting, unspecified",
    },
    questions: [
      {
        question: "How old is the patient?",
        question_type: "multi-choice",
        options: ["18 years or older", "Under 18 years"],
      },
      {
        question: "What is the diagnosis or reason for treatment?",
        question_type: "multi-choice",
        options: [
          "Prevention of nausea and vomiting (acute and delayed) associated with initial and repeat courses of highly or moderately emetogenic cancer chemotherapy",
          "Other",
        ],
      },
      {
        question:
          "Will the requested agent be used in combination with dexamethasone?",
        question_type: "multi-choice",
        options: ["Yes", "No"],
      },
      {
        question:
          "Has the individual tried or is unable to tolerate any of the following formulary alternatives?",
        question_type: "multi-choice",
        options: [
          "Fosaprepitant",
          "Granisetron",
          "Metoclopramide",
          "Ondansetron",
          "Palonosetron",
          "None / Not tried",
        ],
      },
      {
        question:
          "Is the request for initial or repeat course of chemotherapy?",
        question_type: "multi-choice",
        options: ["Initial course", "Repeat course"],
      },
    ],
    pdf_path: "/clinical_pdf/akynzeo.pdf",
    questions_for_ui: [
      {
        question: "How old is the patient?",
        type: "multi-choice",
        options: ["18 years or older", "Under 18 years"],
      },
      {
        question: "What is the diagnosis or reason for treatment?",
        type: "multi-choice",
        options: [
          "Prevention of nausea and vomiting (acute and delayed) associated with initial and repeat courses of highly or moderately emetogenic cancer chemotherapy",
          "Other",
        ],
      },
      {
        question:
          "Will the requested agent be used in combination with dexamethasone?",
        type: "multi-choice",
        options: ["Yes", "No"],
      },
      {
        question:
          "Has the individual tried or is unable to tolerate any of the following formulary alternatives?",
        type: "multi-choice",
        options: [
          "Fosaprepitant",
          "Granisetron",
          "Metoclopramide",
          "Ondansetron",
          "Palonosetron",
          "None / Not tried",
        ],
      },
      {
        question:
          "Is the request for initial or repeat course of chemotherapy?",
        type: "multi-choice",
        options: ["Initial course", "Repeat course"],
      },
    ],
    oncoemr_medicine_summary: [
      {
        identifier: "f5ca9b2e-728c-4b3e-a821-3576bfd01f80",
        patient_mrn: "8778374",
        drug_name: "Akynzeo",
        regimen_description:
          "Akynzeo (fosnetupitant) 235 mg-0.25 mg/20 mL intravenous solution",
        created_at: "2025-10-01 03:35:58.318174 UTC",
        drug_quantity: "40 milliliters",
        drug_refill_quantity: "6",
        regimen_instruction:
          "INFUSE INTRAVENOUSLY 0.25MG EVERY 14 DAYS WITH CHEMOTHERAPY",
        is_best_match: "true",
        is_substitution_allowed: "true",
      },
      {
        identifier: "f5ca9b2e-728c-4b3e-a821-3576bfd01f80",
        patient_mrn: "8778374",
        drug_name: "Akynzeo",
        regimen_description: "oxaliplatin 100 mg/20 mL intravenous solution",
        created_at: "2025-10-01 03:35:58.517950 UTC",
        drug_quantity: "80 milliliters",
        drug_refill_quantity: "11",
        regimen_instruction: "INFUSE 166 MG INTRAVENOUSLY EVERY 2 WEEKS",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "f5ca9b2e-728c-4b3e-a821-3576bfd01f80",
        patient_mrn: "8778374",
        drug_name: "Akynzeo",
        regimen_description: "Udenyca 6 mg/0.6 mL subcutaneous syringe",
        created_at: "2025-10-01 03:35:58.703002 UTC",
        drug_quantity: "1.2 milliliters",
        drug_refill_quantity: "11",
        regimen_instruction:
          "INJECT 6MG SQ 24-48 HOURS POST CHEMOTHERAPY EVERY 14 DAYS",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "f5ca9b2e-728c-4b3e-a821-3576bfd01f80",
        patient_mrn: "8778374",
        drug_name: "Akynzeo",
        regimen_description: "loperamide 2 mg capsule",
        created_at: "2025-10-01 03:35:58.909398 UTC",
        drug_quantity: "180 capsules",
        drug_refill_quantity: "1",
        regimen_instruction:
          "Initial: 4 mg, followed by 2 mg every 2 to 4 hours or after each loose stool as needed for chemo induced diarrhea",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "f5ca9b2e-728c-4b3e-a821-3576bfd01f80",
        patient_mrn: "8778374",
        drug_name: "Akynzeo",
        regimen_description: "metformin 500 mg tablet",
        created_at: "2025-10-01 03:35:59.028251 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: "2 tablets daily",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "f5ca9b2e-728c-4b3e-a821-3576bfd01f80",
        patient_mrn: "8778374",
        drug_name: "Akynzeo",
        regimen_description: "ondansetron 4 mg disintegrating tablet",
        created_at: "2025-10-01 03:35:59.207209 UTC",
        drug_quantity: "120 tablets",
        drug_refill_quantity: "1",
        regimen_instruction:
          "Take 1 tablet every 6-8 hrs as needed for chemo induced n/v",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "f5ca9b2e-728c-4b3e-a821-3576bfd01f80",
        patient_mrn: "8778374",
        drug_name: "Akynzeo",
        regimen_description: "AMLODIPINE BESYLATE 5 MG TAB",
        created_at: "2025-10-01 03:35:59.277798 UTC",
        drug_quantity: "90",
        drug_refill_quantity: null,
        regimen_instruction:
          "TAKE 1 TABLET EVERY DAY BY ORAL ROUTE IN THE MORNING.",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "f5ca9b2e-728c-4b3e-a821-3576bfd01f80",
        patient_mrn: "8778374",
        drug_name: "Akynzeo",
        regimen_description: "LEVOTHYROXINE 100 MCG TABLET",
        created_at: "2025-10-01 03:35:59.327365 UTC",
        drug_quantity: "90",
        drug_refill_quantity: null,
        regimen_instruction: "TAKE 1 TABLET BY MOUTH EVERY DAY",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "f5ca9b2e-728c-4b3e-a821-3576bfd01f80",
        patient_mrn: "8778374",
        drug_name: "Akynzeo",
        regimen_description: "ROSUVASTATIN CALCIUM 20 MG TAB",
        created_at: "2025-10-01 03:35:59.418458 UTC",
        drug_quantity: "90",
        drug_refill_quantity: null,
        regimen_instruction: "TAKE 1 TABLET BY MOUTH EVERY DAY",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "f5ca9b2e-728c-4b3e-a821-3576bfd01f80",
        patient_mrn: "8778374",
        drug_name: "Akynzeo",
        regimen_description: "METFORMIN TAB 500MG",
        created_at: "2025-10-01 03:35:59.521668 UTC",
        drug_quantity: "60",
        drug_refill_quantity: null,
        regimen_instruction: null,
        is_best_match: "false",
        is_substitution_allowed: null,
      },
    ],
    is_substitution_allowed: true,
  },
  {
    mrn: "8184614",
    identifier: "73326bd4-3daf-403c-b71f-7ac29326d48b",
    prescription: {
      drug_days_supply: 21,
      drug_name: "Aranesp",
      drug_quantity: 0.6,
    },
    diagnosis: {
      code: "D63.1",
      description: "Anemia in chronic kidney disease",
    },
    questions: [
      {
        question: "Is the request for an expedited review?",
        question_type: "multi-choice",
        options: ["Yes", "No"],
      },
      {
        question: "What is the patient's most recent hemoglobin (Hgb) level?",
        question_type: "multi-choice",
        options: [
          "< 10.0 g/dL",
          "10.1–12.0 g/dL",
          "> 12.0 g/dL",
          "Not documented",
        ],
      },
      {
        question:
          "Does the patient currently receive iron therapy, or has the prescriber confirmed adequate iron stores?",
        question_type: "multi-choice",
        options: [
          "Currently receiving iron therapy",
          "Adequate iron stores confirmed by prescriber",
          "Neither / Not documented",
        ],
      },
      {
        question: "Is the medication being used for an FDA-approved diagnosis?",
        question_type: "multi-choice",
        options: [
          "Yes — for anemia due to myelosuppressive chemotherapy (non-curative intent)",
          "Yes — for anemia associated with myelodysplastic syndrome (MDS)",
          "Yes — for anemia due to chronic kidney disease (CKD)",
          "No — off-label or non-covered indication",
        ],
      },
      {
        question:
          "Has the member had an inadequate response or intolerance to two formulary alternatives (e.g., epoetin alfa, Retacrit)?",
        question_type: "multi-choice",
        options: ["Yes", "No"],
      },
    ],
    pdf_path: "/clinical_pdf/aranesp.pdf",
    questions_for_ui: [
      {
        question: "Is the request for an expedited review?",
        type: "multi-choice",
        options: ["Yes", "No"],
      },
      {
        question: "What is the patient's most recent hemoglobin (Hgb) level?",
        type: "multi-choice",
        options: [
          "< 10.0 g/dL",
          "10.1–12.0 g/dL",
          "> 12.0 g/dL",
          "Not documented",
        ],
      },
      {
        question:
          "Does the patient currently receive iron therapy, or has the prescriber confirmed adequate iron stores?",
        type: "multi-choice",
        options: [
          "Currently receiving iron therapy",
          "Adequate iron stores confirmed by prescriber",
          "Neither / Not documented",
        ],
      },
      {
        question: "Is the medication being used for an FDA-approved diagnosis?",
        type: "multi-choice",
        options: [
          "Yes — for anemia due to myelosuppressive chemotherapy (non-curative intent)",
          "Yes — for anemia associated with myelodysplastic syndrome (MDS)",
          "Yes — for anemia due to chronic kidney disease (CKD)",
          "No — off-label or non-covered indication",
        ],
      },
      {
        question:
          "Has the member had an inadequate response or intolerance to two formulary alternatives (e.g., epoetin alfa, Retacrit)?",
        type: "multi-choice",
        options: ["Yes", "No"],
      },
    ],
    oncoemr_medicine_summary: [
      {
        identifier: "73326bd4-3daf-403c-b71f-7ac29326d48b",
        patient_mrn: "8184614",
        drug_name: "Aranesp",
        regimen_description: "quetiapine 25 mg tablet",
        created_at: "2025-09-25 04:02:00.202467 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: null,
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "73326bd4-3daf-403c-b71f-7ac29326d48b",
        patient_mrn: "8184614",
        drug_name: "Aranesp",
        regimen_description: "timolol 0.5 % eye drops",
        created_at: "2025-09-25 04:02:00.232814 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: null,
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "73326bd4-3daf-403c-b71f-7ac29326d48b",
        patient_mrn: "8184614",
        drug_name: "Aranesp",
        regimen_description: "gabapentin 800 mg tablet",
        created_at: "2025-09-25 04:02:00.376943 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: null,
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "73326bd4-3daf-403c-b71f-7ac29326d48b",
        patient_mrn: "8184614",
        drug_name: "Aranesp",
        regimen_description: "valsartan 80 mg tablet",
        created_at: "2025-09-25 04:02:00.416319 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: null,
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "73326bd4-3daf-403c-b71f-7ac29326d48b",
        patient_mrn: "8184614",
        drug_name: "Aranesp",
        regimen_description:
          "Aranesp 300 mcg/0.6 mL (in polysorbate) injection syringe",
        created_at: "2025-09-25 04:02:00.131277 UTC",
        drug_quantity: "0.6 milliliters",
        drug_refill_quantity: "11",
        regimen_instruction:
          "INJECT 300MCG SUBCUTANEOUSLY EVERY 3 WEEKS FOR HGB LESS THAN 11",
        is_best_match: "true",
        is_substitution_allowed: "true",
      },
    ],
    is_substitution_allowed: true,
  },
  {
    mrn: "8751692",
    identifier: "2701593a-b817-4375-84f4-e2affb908d06",
    prescription: {
      drug_days_supply: 21,
      drug_name: "Keytruda",
      drug_quantity: 8,
    },
    diagnosis: {
      code: "C34.91",
      description:
        "Malignant neoplasm of unspecified part of right bronchus or lung",
    },
    questions: [
      {
        question:
          "What is the stage and treatment intent for the patient's non-small cell lung cancer (NSCLC)?",
        question_type: "multi-choice",
        options: [
          "Stage IIIb",
          "Stage IV (metastatic)",
          "Other (specify below)",
        ],
      },
      {
        question:
          "Will Keytruda be used in combination with pemetrexed and a platinum agent (cisplatin or carboplatin)?",
        question_type: "multi-choice",
        options: ["Yes", "No"],
      },
      {
        question:
          "Has molecular testing confirmed absence of actionable mutations (e.g., EGFR, ALK, ROS1)?",
        question_type: "multi-choice",
        options: [
          "No actionable mutation detected",
          "Actionable mutation present",
          "Not tested / pending",
        ],
      },
      {
        question:
          "Has the patient received any prior anti-PD-1, anti-PD-L1, or systemic therapy for metastatic disease?",
        question_type: "multi-choice",
        options: ["No", "Yes"],
      },
      {
        question: "What is the patient's current ECOG performance status?",
        question_type: "multi-choice",
        options: [
          "0 — Fully active",
          "1 — Restricted in strenuous activity",
          "2 — Ambulatory >50% of time",
          "≥ 3 — Limited self-care / bedridden",
        ],
      },
    ],
    questions_for_ui: [
      {
        question:
          "What is the stage and treatment intent for the patient's non-small cell lung cancer (NSCLC)?",
        type: "multi-choice",
        options: [
          "Stage IIIb",
          "Stage IV (metastatic)",
          "Other (specify below)",
        ],
      },
      {
        question:
          "Will Keytruda be used in combination with pemetrexed and a platinum agent (cisplatin or carboplatin)?",
        type: "multi-choice",
        options: ["Yes", "No"],
      },
      {
        question:
          "Has molecular testing confirmed absence of actionable mutations (e.g., EGFR, ALK, ROS1)?",
        type: "multi-choice",
        options: [
          "No actionable mutation detected",
          "Actionable mutation present",
          "Not tested / pending",
        ],
      },
      {
        question:
          "Has the patient received any prior anti-PD-1, anti-PD-L1, or systemic therapy for metastatic disease?",
        type: "multi-choice",
        options: ["No", "Yes"],
      },
      {
        question: "What is the patient's current ECOG performance status?",
        type: "multi-choice",
        options: [
          "0 — Fully active",
          "1 — Restricted in strenuous activity",
          "2 — Ambulatory >50% of time",
          "≥ 3 — Limited self-care / bedridden",
        ],
      },
    ],
    pdf_path: "/clinical_pdf/keytruda.pdf",
    oncoemr_medicine_summary: [
      {
        identifier: "2701593a-b817-4375-84f4-e2affb908d06",
        patient_mrn: "8751692",
        drug_name: "Keytruda",
        regimen_description: "Keytruda 25 mg/mL intravenous solution",
        created_at: "2025-08-19 01:34:00.192552 UTC",
        drug_quantity: "8 milliliters",
        drug_refill_quantity: "6",
        regimen_instruction: "INFUSE 200MG INTRAVENOUSLY EVERY 21 DAYS",
        is_best_match: "true",
        is_substitution_allowed: "true",
      },
      {
        identifier: "2701593a-b817-4375-84f4-e2affb908d06",
        patient_mrn: "8751692",
        drug_name: "Keytruda",
        regimen_description: "ATORVASTATIN CALCIUM 40 MG TABS",
        created_at: "2025-08-19 01:34:00.231902 UTC",
        drug_quantity: "90",
        drug_refill_quantity: null,
        regimen_instruction: null,
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "2701593a-b817-4375-84f4-e2affb908d06",
        patient_mrn: "8751692",
        drug_name: "Keytruda",
        regimen_description: "AMLODIPINE BESYLATE 5 MG TAB",
        created_at: "2025-08-19 01:34:00.268910 UTC",
        drug_quantity: "180",
        drug_refill_quantity: null,
        regimen_instruction: "TAKE 1 TABLET BY MOUTH TWICE A DAY",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "2701593a-b817-4375-84f4-e2affb908d06",
        patient_mrn: "8751692",
        drug_name: "Keytruda",
        regimen_description: "NITROGLYCERIN 0.4 MG TABLET SL",
        created_at: "2025-08-19 01:34:00.306953 UTC",
        drug_quantity: "100",
        drug_refill_quantity: null,
        regimen_instruction:
          "USE 1 TABLET SUBLINGUALLY AS NEEDED FOR CHEST PAIN",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "2701593a-b817-4375-84f4-e2affb908d06",
        patient_mrn: "8751692",
        drug_name: "Keytruda",
        regimen_description: "CARVEDILOL 6.25 MG TABLET",
        created_at: "2025-08-19 01:34:00.342935 UTC",
        drug_quantity: "180",
        drug_refill_quantity: null,
        regimen_instruction:
          "TAKE 1 TABLET TWICE A DAY WITH MEAL ORAL TWICE A DAY",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "2701593a-b817-4375-84f4-e2affb908d06",
        patient_mrn: "8751692",
        drug_name: "Keytruda",
        regimen_description: "ENALAPRIL MALEATE 10 MG TABS",
        created_at: "2025-08-19 01:34:00.378500 UTC",
        drug_quantity: "90",
        drug_refill_quantity: null,
        regimen_instruction: null,
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "2701593a-b817-4375-84f4-e2affb908d06",
        patient_mrn: "8751692",
        drug_name: "Keytruda",
        regimen_description: "ALBUTEROL HFA 90 MCG INHALER",
        created_at: "2025-08-19 01:34:00.416070 UTC",
        drug_quantity: "20.1",
        drug_refill_quantity: null,
        regimen_instruction:
          "INHALE 1 TO 2 PUFFS BY MOUTH EVERY 4 TO 6 HOURS AS NEEDED",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
    ],
    is_substitution_allowed: true,
  },
  {
    mrn: "7801005",
    identifier: "eafd3fe0-f742-406c-87a6-a5ddc8c7b24a",
    prescription: {
      drug_days_supply: 21,
      drug_name: "Mvasi",
      drug_quantity: 20,
    },
    diagnosis: {
      code: "C18.7",
      description:
        "Colon Cancer (Gastrointestinal) - Clinical Stage I (AJCC v8)",
    },
    pdf_path: "/clinical_pdf/mvasi.pdf",
    questions: [
      {
        question: "What is the diagnosis for the medication being requested?",
        question_type: "multi-choice",
        options: [
          "Metastatic Colorectal Cancer (mCRC)",
          "Central Nervous System (CNS) – Primary Tumor",
          "Cervical Cancer (Persistent / Recurrent / Metastatic)",
          "Epithelial Ovarian / Fallopian Tube / Primary Peritoneal Cancer",
          "Renal Cell Carcinoma (mRCC)",
          "Non–Small Cell Lung Cancer (NSCLC) – Non-squamous",
        ],
      },
      {
        question:
          "Has the individual progressed on more than two lines of bevacizumab-containing chemotherapy?",
        question_type: "multi-choice",
        options: ["Yes", "No", "Not Documented"],
      },
      {
        question:
          "Is the individual ineligible for or has the individual progressed on checkpoint inhibitor immunotherapy (e.g., pembrolizumab, nivolumab)?",
        question_type: "multi-choice",
        options: ["Yes", "No", "Not applicable"],
      },
      {
        question: "Select the regimen in which Mvasi will be used:",
        question_type: "multi-choice",
        options: [
          "In combination with 5-fluorouracil–based chemotherapy",
          "In combination with irinotecan",
          "In combination with oxaliplatin",
          "In combination with trifluridine + tipiracil (Lonsurf) after standard therapies",
          "Other",
        ],
      },
      {
        question: "Confirm the total bevacizumab dosing and frequency:",
        question_type: "multi-choice",
        options: [
          "≤ 5 mg/kg IV q2 weeks (with bolus-IFL)",
          "≤ 10 mg/kg IV q2 weeks (with FOLFOX4)",
          "≤ 5 mg/kg IV q2 weeks or 7.5 mg/kg IV q3 weeks (with fluoropyrimidine-irinotecan/oxaliplatin after prior bevacizumab)",
          "Dose exceeds above parameters",
        ],
      },
    ],
    questions_for_ui: [
      {
        question: "What is the diagnosis for the medication being requested?",
        type: "multi-choice",
        options: [
          "Metastatic Colorectal Cancer (mCRC)",
          "Central Nervous System (CNS) – Primary Tumor",
          "Cervical Cancer (Persistent / Recurrent / Metastatic)",
          "Epithelial Ovarian / Fallopian Tube / Primary Peritoneal Cancer",
          "Renal Cell Carcinoma (mRCC)",
          "Non–Small Cell Lung Cancer (NSCLC) – Non-squamous",
        ],
      },
      {
        question:
          "Has the individual progressed on more than two lines of bevacizumab-containing chemotherapy?",
        type: "multi-choice",
        options: ["Yes", "No", "Not Documented"],
      },
      {
        question:
          "Is the individual ineligible for or has the individual progressed on checkpoint inhibitor immunotherapy (e.g., pembrolizumab, nivolumab)?",
        type: "multi-choice",
        options: ["Yes", "No", "Not applicable"],
      },
      {
        question: "Select the regimen in which Mvasi will be used:",
        type: "multi-choice",
        options: [
          "In combination with 5-fluorouracil–based chemotherapy",
          "In combination with irinotecan",
          "In combination with oxaliplatin",
          "In combination with trifluridine + tipiracil (Lonsurf) after standard therapies",
          "Other",
        ],
      },
      {
        question: "Confirm the total bevacizumab dosing and frequency:",
        type: "multi-choice",
        options: [
          "≤ 5 mg/kg IV q2 weeks (with bolus-IFL)",
          "≤ 10 mg/kg IV q2 weeks (with FOLFOX4)",
          "≤ 5 mg/kg IV q2 weeks or 7.5 mg/kg IV q3 weeks (with fluoropyrimidine-irinotecan/oxaliplatin after prior bevacizumab)",
          "Dose exceeds above parameters",
        ],
      },
    ],
    oncoemr_medicine_summary: [
      {
        identifier: "eafd3fe0-f742-406c-87a6-a5ddc8c7b24a",
        patient_mrn: "7801005",
        drug_name: "Mvasi",
        regimen_description: "capecitabine 150 mg tablet",
        created_at: "2025-08-19 01:44:40.047255 UTC",
        drug_quantity: "84 tablets",
        drug_refill_quantity: "4",
        regimen_instruction:
          "TAKE 3 TABLET (450MG) BY MOUTH TWICE DAILY 2 WEEKS ON 1 WEEK OFF",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "eafd3fe0-f742-406c-87a6-a5ddc8c7b24a",
        patient_mrn: "7801005",
        drug_name: "Mvasi",
        regimen_description: "capecitabine 500 mg tablet",
        created_at: "2025-08-19 01:44:40.084698 UTC",
        drug_quantity: "56 tablets",
        drug_refill_quantity: "4",
        regimen_instruction:
          "TAKE 2 TABLETS BY MOUTH TWICE DAILY (1000MG BID) 2 WEEKS ON 1 WEEK OFF",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "eafd3fe0-f742-406c-87a6-a5ddc8c7b24a",
        patient_mrn: "7801005",
        drug_name: "Mvasi",
        regimen_description: "Mvasi 25 mg/mL intravenous solution",
        created_at: "2025-08-19 01:44:43.334668 UTC",
        drug_quantity: "20 milliliters",
        drug_refill_quantity: "7",
        regimen_instruction: "INFUSE 487MG INTRAVENOUSLY EVERY 3 WEEKS",
        is_best_match: "true",
        is_substitution_allowed: "true",
      },
      {
        identifier: "eafd3fe0-f742-406c-87a6-a5ddc8c7b24a",
        patient_mrn: "7801005",
        drug_name: "Mvasi",
        regimen_description: "Injectafer 50 mg iron/mL intravenous solution",
        created_at: "2025-08-19 01:44:43.376800 UTC",
        drug_quantity: "15 milliliters",
        drug_refill_quantity: "2",
        regimen_instruction: "INFUSE 750MG INTRAVENOUSLY x 1 dose",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "eafd3fe0-f742-406c-87a6-a5ddc8c7b24a",
        patient_mrn: "7801005",
        drug_name: "Mvasi",
        regimen_description: "ondansetron 8 mg disintegrating tablet",
        created_at: "2025-08-19 01:44:43.411944 UTC",
        drug_quantity: "30 tablets",
        drug_refill_quantity: null,
        regimen_instruction:
          "Place 1 tab on tongue every 6-8 hours prn for nausea",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "eafd3fe0-f742-406c-87a6-a5ddc8c7b24a",
        patient_mrn: "7801005",
        drug_name: "Mvasi",
        regimen_description: "capecitabine 500 mg tablet",
        created_at: "2025-08-19 01:44:43.448455 UTC",
        drug_quantity: "84 tablets",
        drug_refill_quantity: "11",
        regimen_instruction:
          "TAKE 3 TABLETS (1500MG) BY MOUTH TWICE DAILY DAYS 1-14 EVERY 21 DAY CYCLE",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "eafd3fe0-f742-406c-87a6-a5ddc8c7b24a",
        patient_mrn: "7801005",
        drug_name: "Mvasi",
        regimen_description: "doxycycline hyclate 20 mg tablet",
        created_at: "2025-08-19 01:44:43.486043 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction:
          "pt does not know dosage will be followed up on next visit",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "eafd3fe0-f742-406c-87a6-a5ddc8c7b24a",
        patient_mrn: "7801005",
        drug_name: "Mvasi",
        regimen_description: "Augmentin 500 mg-125 mg tablet",
        created_at: "2025-08-19 01:44:43.521591 UTC",
        drug_quantity: "14 tablets",
        drug_refill_quantity: null,
        regimen_instruction: "1 p.o. twice a day (BID)",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "eafd3fe0-f742-406c-87a6-a5ddc8c7b24a",
        patient_mrn: "7801005",
        drug_name: "Mvasi",
        regimen_description: "Macrobid 100 mg capsule",
        created_at: "2025-08-19 01:44:43.555408 UTC",
        drug_quantity: "14 capsules",
        drug_refill_quantity: null,
        regimen_instruction: "1 p.o. twice a day (BID)",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "eafd3fe0-f742-406c-87a6-a5ddc8c7b24a",
        patient_mrn: "7801005",
        drug_name: "Mvasi",
        regimen_description: "Macrobid 100 mg capsule",
        created_at: "2025-08-19 01:44:43.589415 UTC",
        drug_quantity: "14 capsules",
        drug_refill_quantity: null,
        regimen_instruction: "1 p.o. twice a day (BID)",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "eafd3fe0-f742-406c-87a6-a5ddc8c7b24a",
        patient_mrn: "7801005",
        drug_name: "Mvasi",
        regimen_description: "Injectafer 50 mg iron/mL intravenous solution",
        created_at: "2025-08-19 01:44:43.626127 UTC",
        drug_quantity: "30 milliliters",
        drug_refill_quantity: "3",
        regimen_instruction: "INFUSE 750MG IV ON DAYS 1 & 8",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "eafd3fe0-f742-406c-87a6-a5ddc8c7b24a",
        patient_mrn: "7801005",
        drug_name: "Mvasi",
        regimen_description: "Paxil 40 mg tablet",
        created_at: "2025-08-19 01:44:43.661035 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: "1 p.o. q. day",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "eafd3fe0-f742-406c-87a6-a5ddc8c7b24a",
        patient_mrn: "7801005",
        drug_name: "Mvasi",
        regimen_description: "Vitamin B-12 1,000 mcg tablet",
        created_at: "2025-08-19 01:44:43.697373 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: "1 p.o. q. day",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "eafd3fe0-f742-406c-87a6-a5ddc8c7b24a",
        patient_mrn: "7801005",
        drug_name: "Mvasi",
        regimen_description: "Calcium 500 500 mg calcium (1,250 mg) tablet",
        created_at: "2025-08-19 01:44:43.737560 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: "1 p.o. q. day",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "eafd3fe0-f742-406c-87a6-a5ddc8c7b24a",
        patient_mrn: "7801005",
        drug_name: "Mvasi",
        regimen_description:
          "iron ER 159 mg (45 mg iron) tablet,extended release",
        created_at: "2025-08-19 01:44:43.774614 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: "1 p.o. q. day",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "eafd3fe0-f742-406c-87a6-a5ddc8c7b24a",
        patient_mrn: "7801005",
        drug_name: "Mvasi",
        regimen_description: "Lipitor 10 mg tablet",
        created_at: "2025-08-19 01:44:43.810747 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: "1 p.o. q. day",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "eafd3fe0-f742-406c-87a6-a5ddc8c7b24a",
        patient_mrn: "7801005",
        drug_name: "Mvasi",
        regimen_description: "losartan 25 mg tablet",
        created_at: "2025-08-19 01:44:43.845042 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: "1 p.o. q. day unsure dose",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "eafd3fe0-f742-406c-87a6-a5ddc8c7b24a",
        patient_mrn: "7801005",
        drug_name: "Mvasi",
        regimen_description:
          "Wellbutrin XL 150 mg 24 hr tablet, extended release",
        created_at: "2025-08-19 01:44:43.879822 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: "450mg 1 p.o. q. day",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
    ],
    is_substitution_allowed: true,
  },
  {
    mrn: "8742953",
    identifier: "38401cc7-efed-4802-b9a9-b92320143fe1",
    prescription: {
      drug_days_supply: 21,
      drug_name: "Udenyca",
      drug_quantity: 0.6,
    },
    diagnosis: {
      code: "D70.9",
      description: "Neutropenia, unspecified",
    },
    questions: [
      {
        question: "What is the indication for use of Udenyca?",
        question_type: "multi-choice",
        options: [
          "Primary prophylaxis of febrile neutropenia (FN) in a patient receiving myelosuppressive chemotherapy",
          "Secondary prophylaxis (after prior FN episode)",
          "Treatment of existing neutropenia",
        ],
      },
      {
        question:
          "Is the patient receiving a chemotherapy regimen associated with ≥ 20% risk of febrile neutropenia (FN)?",
        question_type: "multi-choice",
        options: ["Yes", "No"],
      },
      {
        question:
          "Is the requested medication prescribed by or in consultation with a hematologist or oncologist?",
        question_type: "multi-choice",
        options: ["Yes", "No"],
      },
      {
        question:
          "Has the patient tried or demonstrated intolerance/inadequate response to any preferred biosimilar products?",
        question_type: "multi-choice",
        options: [
          "Yes — Fylnetra",
          "Yes — Nyvepria",
          "Yes — Fulphila",
          "Yes — Neulasta",
          "Yes — Ziextenzo",
          "No preferred product tried",
        ],
      },
      {
        question:
          "Is the request for prophylactic use following each chemotherapy cycle (single 6 mg SC dose ≥24 hours after chemo)?",
        question_type: "multi-choice",
        options: ["Yes", "No"],
      },
    ],
    questions_for_ui: [
      {
        question: "What is the indication for use of Udenyca?",
        type: "multi-choice",
        options: [
          "Primary prophylaxis of febrile neutropenia (FN) in a patient receiving myelosuppressive chemotherapy",
          "Secondary prophylaxis (after prior FN episode)",
          "Treatment of existing neutropenia",
        ],
      },
      {
        question:
          "Is the patient receiving a chemotherapy regimen associated with ≥ 20% risk of febrile neutropenia (FN)?",
        type: "multi-choice",
        options: ["Yes", "No"],
      },
      {
        question:
          "Is the requested medication prescribed by or in consultation with a hematologist or oncologist?",
        type: "multi-choice",
        options: ["Yes", "No"],
      },
      {
        question:
          "Has the patient tried or demonstrated intolerance/inadequate response to any preferred biosimilar products?",
        type: "multi-choice",
        options: [
          "Yes — Fylnetra",
          "Yes — Nyvepria",
          "Yes — Fulphila",
          "Yes — Neulasta",
          "Yes — Ziextenzo",
          "No preferred product tried",
        ],
      },
      {
        question:
          "Is the request for prophylactic use following each chemotherapy cycle (single 6 mg SC dose ≥24 hours after chemo)?",
        type: "multi-choice",
        options: ["Yes", "No"],
      },
    ],
    pdf_path: "/clinical_pdf/udenyca.pdf",
    oncoemr_medicine_summary: [
      {
        identifier: "38401cc7-efed-4802-b9a9-b92320143fe1",
        patient_mrn: "8742953",
        drug_name: "Udenyca",
        regimen_description: "pt reports no meds.",
        created_at: "2025-08-28 00:56:14.911699 UTC",
        drug_quantity: null,
        drug_refill_quantity: null,
        regimen_instruction: null,
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "38401cc7-efed-4802-b9a9-b92320143fe1",
        patient_mrn: "8742953",
        drug_name: "Udenyca",
        regimen_description: "Udenyca 6 mg/0.6 mL subcutaneous syringe",
        created_at: "2025-08-28 00:56:14.818638 UTC",
        drug_quantity: "0.6 milliliters",
        drug_refill_quantity: "7",
        regimen_instruction:
          "INJECT 6MG SUBCUTANEOUSLY EVERY 3 WEEKS POST CHEMOTHERAPY",
        is_best_match: "true",
        is_substitution_allowed: "true",
      },
      {
        identifier: "38401cc7-efed-4802-b9a9-b92320143fe1",
        patient_mrn: "8742953",
        drug_name: "Udenyca",
        regimen_description:
          "Udenyca Onbody 6 mg/0.6 mL with wearable subcutaneous injector",
        created_at: "2025-08-28 00:56:14.865765 UTC",
        drug_quantity: "0.6 milliliters",
        drug_refill_quantity: "7",
        regimen_instruction:
          "APPLY 6MG ON BODY INJECTOR SUBCUTANEOUSLY EVERY 21 DAYS",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "38401cc7-efed-4802-b9a9-b92320143fe1",
        patient_mrn: "8742953",
        drug_name: "Udenyca",
        regimen_description:
          "Akynzeo (fosnetupitant) 235 mg-0.25 mg/20 mL intravenous solution",
        created_at: "2025-08-28 00:56:11.438670 UTC",
        drug_quantity: "20 milliliters",
        drug_refill_quantity: "7",
        regimen_instruction:
          "INFUSE INTRAVENOUSLY 0.25MG EVERY 21 DAYS WITH CHEMOTHERAPY",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "38401cc7-efed-4802-b9a9-b92320143fe1",
        patient_mrn: "8742953",
        drug_name: "Udenyca",
        regimen_description: "dexamethasone 4 mg tablet",
        created_at: "2025-08-28 00:56:11.480684 UTC",
        drug_quantity: "20 tablets",
        drug_refill_quantity: "3",
        regimen_instruction: "take 2 tabs 24 and 12 hours prior to chemo",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
      {
        identifier: "38401cc7-efed-4802-b9a9-b92320143fe1",
        patient_mrn: "8742953",
        drug_name: "Udenyca",
        regimen_description: "ondansetron 8 mg disintegrating tablet",
        created_at: "2025-08-28 00:56:11.522790 UTC",
        drug_quantity: "60 tablets",
        drug_refill_quantity: "3",
        regimen_instruction: "1 tab q 8-12 hour prn nausea",
        is_best_match: "false",
        is_substitution_allowed: null,
      },
    ],
    is_substitution_allowed: true,
  },
];
